# Generated by Django 3.1.2 on 2020-10-14 18:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201004_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=35)),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
            managers=[
                ('comentarios', django.db.models.manager.Manager()),
            ],
        ),
    ]
